### ISSUE TITLE
Adding new URL causes this error

### ISSUE THREAD

**Issue by chrzrdx** [Shinu007/Website_Word_counter#9]
```
127.0.0.1 - - [27/Mar/2020 11:00:04] "GET /dashboard HTTP/1.1" 200 -
127.0.0.1 - - [27/Mar/2020 11:00:08] "GET /add-task HTTP/1.1" 200 -
127.0.0.1 - - [27/Mar/2020 11:00:17] "POST /add-task HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chr/edyst/Website_Word_counter/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/chr/edyst/Website_Word_counter/Main/Main.py", line 163, in add_task
    new_result = Results(time=strftime('%a, %d %b %Y %H:%M:%S'),username=current_user.username,url=form.url.data,jobId=task.id,Createdat=task.enqueued_at.strftime('%a, %d %b %Y %H:%M:%S'),Enqueuedat=task.enqueued_at.strftime("%c"),Finishedat=task.ended_at.strftime('%a, %d %b %Y %H:%M:%S'),Status="Success",wordcount=count_words(form.url.data))
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by dxter6** [comment]
fixed
